package: "fuzzy_water_clustering"
  name: "fuzzy_clustering"
  version: "0.0.3"

source:
  git_rev: "0.0.3"
  git_url: "https://gitlab.rsg.pml.ac.uk/Angus/fuzzy_classifcation"

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - fuzzy_water_clustering

about:
  home: "https://gitlab.rsg.pml.ac.uk/Angus/fuzzy_classifcation/"
