{% set name = "fuzzy_water_clustering" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://gitlab.rsg.pml.ac.uk/Angus/fuzzy_classifcation
  git_rev: master

# build:
#   number: 1
#   script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    # - pip
    - python

  run:
    - python

test:
  imports:
    - fuzzy_water_clustering

about:
  home: https://gitlab.rsg.pml.ac.uk/Angus/fuzzy_classifcation
  license: BSD
  license_family: BSD
  summary: Scikit-learn compatible fuzzy clustering estimators, plus utils
